### ISSUE TITLE
... but what does it do?

### ISSUE THREAD

**Issue by durera** [ibm-watson-iot/iot-platform-bluemix-starter#2]
What does this starter app actually do?  After reading the readme I'm no more informed as to what the application does after it's been deployed, the readme covers in great detail how to deploy it, but offers little/no information about the application itself and what it does.

**Comment by mzuliani-ibm** [comment]
Thanks for the feedback, I'll take another stab at the readme to align & improve upon the text we've already got around the Starter boilerplate in the catalog and the docs.
https://console.ng.bluemix.net/catalog/starters/internet-of-things-platform-starter/
says:

> **Internet of Things Platform Starter**
> Get started with IBM Watson IoT platform using the Node-RED Node.js sample application. With the Starter, you can quickly simulate an Internet of Things device, create cards, generate data, and begin analyzing and displaying data in the Watson IoT Platform dashboard.

Docs: https://www.ng.bluemix.net/docs/#starters/IoT/iot500.html#iot500
